
##配置数据源
##应先导入数据库依赖
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.10:3306/douyamall_sms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
##配置MyBatis-Plus
##主类上添加MapperScan
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto   #自增主键


#server:
#  port: 7000
logging:
  level:
    org.lanjianghao.douyamall: debug
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  zipkin:
    base-url: http://172.16.2.132:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
feign:
  sentinel:
    enabled: true