server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.2.132:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  thymeleaf:
    cache: false
  redis:
    host: 172.16.2.132
    port: 6379
  session:
    store-type: redis
  zipkin:
    base-url: http://172.16.2.132:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    org.lanjianghao: debug

douyamall:
  thread-pool:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

feign:
  sentinel:
    enabled: true