spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.2.132:8848

    gateway:
      routes:
        - id : product_route
          uri: lb://douyamall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: member_route
          uri: lb://douyamall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: ware_route
          uri: lb://douyamall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: third_party_route
          uri: lb://douyamall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters: # http://localhost:88/api/captcha.jpg => http://localhost:8080/renren-fast/captcha.jpg
            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:    # http://localhost:88/api/captcha.jpg => http://localhost:8080/renren-fast/captcha.jpg
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

        - id: host_route
          uri: lb://douyamall-product
          predicates:
            - Host=douyamall.com, item.douyamall.com

        - id: search_route
          uri: lb://douyamall-search
          predicates:
            - Host=search.douyamall.com

        - id: auth_route
          uri: lb://douyamall-auth
          predicates:
            - Host=auth.douyamall.com

        - id: cart_route
          uri: lb://douyamall-cart
          predicates:
            - Host=cart.douyamall.com

      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowCredentials: true

server:
  port: 88
