spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.2.132:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
      filter:
        enabled: false

    gateway:
      routes:
        - id : product_route
          uri: lb://douyamall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: member_route
          uri: lb://douyamall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: ware_route
          uri: lb://douyamall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: coupon_route
          uri: lb://douyamall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: third_party_route
          uri: lb://douyamall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters: # http://localhost:88/api/captcha.jpg => http://localhost:8080/renren-fast/captcha.jpg
            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:    # http://localhost:88/api/captcha.jpg => http://localhost:8080/renren-fast/captcha.jpg
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

        - id: douyamall_host_route
          uri: lb://douyamall-product
          predicates:
            - Host=douyamall.com, item.douyamall.com

        - id: douyamall_search_route
          uri: lb://douyamall-search
          predicates:
            - Host=search.douyamall.com

        - id: douyamall_auth_route
          uri: lb://douyamall-auth
          predicates:
            - Host=auth.douyamall.com

        - id: douyamall_cart_route
          uri: lb://douyamall-cart
          predicates:
            - Host=cart.douyamall.com

        - id: douyamall_order_route
          uri: lb://douyamall-order
          predicates:
            - Host=order.douyamall.com

        - id: douyamall_member_route
          uri: lb://douyamall-member
          predicates:
            - Host=member.douyamall.com

        - id: douyamall_seckill_route
          uri: lb://douyamall-seckill
          predicates:
            - Host=seckill.douyamall.com

      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowCredentials: true

  zipkin:
    base-url: http://172.16.2.132:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

server:
  port: 88

feign:
  sentinel:
    enabled: true
