#配置数据源
#应先导入数据库依赖
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.16.2.132:3306/douyamall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
    nacos:
      discovery:
        server-addr: 172.16.2.132:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: douyamall-ware
  rabbitmq:
    host: 172.16.2.132
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual    #手动确认模式
  zipkin:
    base-url: http://172.16.2.132:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

#配置MyBatis-Plus
#主类上添加MapperScan
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto   #自增主键

server:
  port: 11000

logging:
  level:
    org.lanjianghao.douyamall: debug
feign:
  sentinel:
    enabled: true