
#配置数据源
#应先导入数据库依赖
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.16.2.132:3306/douyamall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.2.132:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false      # 取消thymeleaf缓存，以便实时看到更新后的页面。另外还需要开启devtools
  redis:
    host: 172.16.2.132
    port: 6379
#    password:
  cache:
    type: redis
    redis:
      time-to-live: 1h
      cache-null-values: true
      key-prefix: CACHE_
      use-key-prefix: true


#配置MyBatis-Plus
#主类上添加MapperScan
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto   #自增主键

      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 10000

logging:
  level:
    org.lanjianghao.douyamall: debug
