server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.2.132:8848
#alibaba:
#  cloud:
#    access-key:
#    secret-key:
#    oss:
#      endpoint: oss-cn-beijing.aliyuncs.com
#      bucket: lanjianghao-douyamall

#短信服务
sms:
  host: https://wwsms.market.alicloudapi.com
  path: /send_sms
  template-id: TPL_0001
  app-code: 963bed44cfa6419981509d118a66daff

