
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.2.132:8848
  application:
    name: douyamall-search
  thymeleaf:
    cache: false
  redis:
    host: 172.16.2.132
    port: 6379
  session:
    store-type: redis
server:
  port: 12000
