
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.2.132:8848
  application:
    name: douyamall-search
  thymeleaf:
    cache: false
  messages:
    basename:
server:
  port: 12000
